### ISSUE TITLE
`get_balance` can panic

### ISSUE THREAD

**Issue by Ximik** [spacesprotocol/spaced#31]
```
thread '<unnamed>' panicked at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-units-0.1.2/src/amount.rs:1107:31:
Amount subtraction error
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:262:5
   3: core::option::expect_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:1995:5
   4: core::option::Option<T>::expect
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:898:21
   5: <bitcoin_units::amount::Amount as core::ops::arith::Sub>::sub
             at /home/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bitcoin-units-0.1.2/src/amount.rs:1107:9
   6: spaced::wallets::RpcWallet::get_balance
             at ./node/src/wallets.rs:180:22
   7: spaced::wallets::RpcWallet::wallet_handle_commands
             at ./node/src/wallets.rs:266:31
   8: spaced::wallets::RpcWallet::wallet_sync
             at ./node/src/wallets.rs:303:17
   9: spaced::wallets::RpcWallet::service::{{closure}}::{{closure}}
             at ./node/src/wallets.rs:774:41
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

The values (`format {}`) right before the panic
```
details.balance.confirmed 0.00003986 BTC
details.balance.trusted_pending 0.00000353 BTC
details.dust 0.00010959 BTC
```

**Comment by buffrr** [comment]
Thanks, I believe this happened because dust also calculates the non trusted pending balance. It should have been fixed [here](https://github.com/spacesprotocol/spaced/blob/d4a85faf3bf1d781c47e5fc187ed4d11e4d5394e/node/src/wallets.rs#L161) in #32 


If that's not the case, please reopen.

**Comment by Ximik** [comment]
Technically you can still have this error.

Start with an empty regtest and do something like

```bash
BITCOIN_CLI="bitcoin-cli -regtest -rpcuser=test -rpcpassword=test"
SPACES_CLI="cargo run --bin space-cli -- --chain regtest"

$BITCOIN_CLI createwallet default
$BITCOIN_CLI generatetoaddress 3500 $($BITCOIN_CLI getnewaddress)

$SPACES_CLI createwallet
$BITCOIN_CLI generatetoaddress 1 $($SPACES_CLI getnewaddress)

$SPACES_CLI balance
```
(panics)

On the other hand, it seems like you can't have that with the "normal" usage

```bash
BITCOIN_CLI="bitcoin-cli -regtest -rpcuser=test -rpcpassword=test"
SPACES_CLI="cargo run --bin space-cli -- --chain regtest"

$SPACES_CLI createwallet

$BITCOIN_CLI createwallet default
$BITCOIN_CLI generatetoaddress 101 $($BITCOIN_CLI getnewaddress)

UTXO=$($BITCOIN_CLI listunspent | jq '[.[] | {txid: .txid, vout: .vout, amount: .amount}][0]')

INPUTS="[{\"txid\":\"$(echo $UTXO | jq -r '.txid')\",\"vout\":$(echo $UTXO | jq -r '.vout')}]"
OUTPUTS="{\"$($SPACES_CLI getnewaddress)\":0.00000001,\"$($BITCOIN_CLI getrawchangeaddress)\":49.9999}"
RAW_TX=$($BITCOIN_CLI createrawtransaction "$INPUTS" "$OUTPUTS")

SIGNED_RESULT=$($BITCOIN_CLI signrawtransactionwithwallet "$RAW_TX")
SIGNED_TX=$(echo "$SIGNED_RESULT" | jq -r '.hex')
TXID=$($BITCOIN_CLI sendrawtransaction "$SIGNED_TX")

$BITCOIN_CLI generateblock $($BITCOIN_CLI getnewaddress) "[\"$TXID\"]"

$SPACES_CLI balance
```
(works fine for me)
